hpb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views # For login page

urlpatterns = [
    url(r'^scheduler/', include('scheduler.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
]

scheduler/urls.py
from django.conf.urls import url

from . import views

app_name = "scheduler"
urlpatterns = [
    # ex: /scheduler/
    url(r'^$', views.index, name='index'),
    # ex: /scheduler/generate/
    url(r'^generate-schedule/$', views.generateSchedule, name='generate-schedule'),
    # ex: /scheduler/generate/edit/
    #url(r'^generate-schedule/edit/$', views.scheduleEdit, name='schedule-edit'),
    # ex: /scheduler/generate/delete/
    url(r'^generate-schedule/delete/$', views.tempScheduleDelete, name='temp-schedule-delete'),
    # ex: /scheduler/generate/save/
    url(r'^generate-schedule/save/$', views.scheduleSave, name='schedule-save'),
    # ex: /scheduler/generate/override/
    url(r'^generate-schedule/override/$', views.scheduleOverride, name='schedule-override'),
    # ex: /scheduler/employees/
    url(r'^employees/$', views.manageEmployees, name='manage-employees'),
    # ex: /scheduler/employees/5/update/
    url(r'^employees/(?P<pk>[0-9]+)/update/$', views.EmployeeUpdate.as_view(), name='employee-update'),
    # ex: /scheduler/employees/5/delete/
    url(r'^employees/(?P<pk>[0-9]+)/delete/$', views.EmployeeDelete.as_view(), name='employee-delete'),
    # ex: /scheduler/requests/
    url(r'^requests/$', views.requests, name='requests'),
    # ex: /scheduler/requests/prompt/
    url(r'^requests/prompt/$', views.requestPrompt, name='request-prompt'),
    # ex: /scheduler/requests/vacation-request/
    url(r'^requests/vacation-request/$', views.vacationRequest.as_view(), name='vacation-request'),
    # ex: /scheduler/requests/shift-request/
    url(r'^requests/shift-request/$', views.shiftRequest.as_view(), name='shift-request'),
    # ex: /scheduler/requests/recurring-shift-request/
    url(r'^requests/recurring-shift-request/$', views.recurringShiftRequest.as_view(), name='recurring-shift-request'),
    # ex: /scheduler/requests/vacation-request/5/update/
    url(r'^requests/vacation-request/(?P<pk>[0-9]+)/update/$', views.VacationRequestUpdate.as_view(), name='vacation-request-update'),
    # ex: /scheduler/requests/vacation-request/5/delete/
    url(r'^requests/vacation-request/(?P<pk>[0-9]+)/delete/$', views.VacationRequestDelete.as_view(), name='vacation-request-delete'),
    # ex: /scheduler/requests/shift-request/5/update/
    url(r'^requests/shift-request/(?P<pk>[0-9]+)/update/$', views.ShiftRequestUpdate.as_view(), name='shift-request-update'),
    # ex: /scheduler/requests/shift-request/5/delete/
    url(r'^requests/shift-request/(?P<pk>[0-9]+)/delete/$', views.ShiftRequestDelete.as_view(), name='shift-request-delete'),
    # ex: /scheduler/requests/recurring-shift-request/5/update/
    url(r'^requests/recurring-shift-request/(?P<pk>[0-9]+)/update/$', views.RecurringShiftRequestUpdate.as_view(), name='recurring-shift-request-update'),
    # ex: /scheduler/requests/recurring-shift-request/5/delete/
    url(r'^requests/recurring-shift-request/(?P<pk>[0-9]+)/delete/$', views.RecurringShiftRequestDelete.as_view(), name='recurring-shift-request-delete'),
    # ex: /scheduler/schedules/
    url(r'^schedules/$', views.schedules, name='schedules'),
    # ex: /scheduler/schedules/yyyy-mm-dd/
    url(r'^schedules/(?P<date>\d{4}-\d{2}-\d{2})/$', views.schedules, name='schedules'),
    # ex: /scheduler/coverage/yyyy-mm-dd/
    url(r'^schedules/coverage/$', views.scheduleCoverage, name='schedule-coverage'),
    url(r'^schedules/coverage/(?P<date>\d{4}-\d{2}-\d{2})/$', views.scheduleCoverage, name='schedule-coverage'),
    # ex: /scheduler/schedules/edit/yyyy-mm-dd/
    url(r'^schedules/edit/$', views.editSchedule, name='schedule-edit'),
    url(r'^schedules/edit/(?P<date>\d{4}-\d{2}-\d{2})/$', views.editSchedule, name='schedule-edit'),
    # ex: /scheduler/schedules/delete/
    url(r'^schedules/delete/$', views.deleteSchedule, name='schedule-delete'),
]

scheduler/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.validators import validate_comma_separated_integer_list, MaxValueValidator
from django.core.exceptions import ValidationError
import datetime

#Constants
SHIFT_CHOICES = (
    ("OFF", "OFF"),
    ("V", "V"),
    ("6am", "6am-2pm"),
    ("7am", "7am-3pm"),
    ("7:30am", "7:30am-3:30pm"),
    ("8am", "8am-4pm"),
    ("9am", "9am-5pm"),
    ("10am", "10am-6pm"),
    ("11am", "11am-7pm"),
    ("12pm", "12pm-8pm"),
    ("1pm", "1pm-9pm"),
    ("1:30pm", "1:30pm-9:30pm"),
    ("2:30pm", "2:30pm-10:30pm"),
    ("3:30pm", "3:30pm-11:30pm"),
)
WEEKDAY_CHOICES = (
    ("M", "Monday"),
    ("T", "Tuesday"),
    ("W", "Wednesday"),
    ("Th", "Thursday"),
    ("F", "Friday"),
    ("Sa", "Saturday"),
    ("Su", "Sunday"),
)

#Validators
def no_past(value):
    today = datetime.date.today()
    if value < today:
        raise ValidationError("Cannot request a date in the past.")

def only_monday(value):
    wkday = value.weekday()
    if not(wkday==1):
        raise ValidationError("Week start must be a Monday.")

# Create your models here.
class Employee(models.Model):
    #Choices for employee position
    POSITION_CHOICES = (
        ("SM", "Senior Manager"),
        ("AM", "Assistant Manager"),
        ("SIM", "Store Inventory Merchandiser"),
        ("SLIM", "Shift Leader"),
        ("BSI", "Bookseller I"),
        ("BSII", "Bookseller II"),
        ("PT", "Part Time Bookseller"),
        ("TB", "Temporary Bookseller"),
    )
    QUAD_CHOICES = ((i+1,i+1) for i in range(4))
    firstName = models.CharField(max_length=20, default="")
    lastName = models.CharField(max_length=20, default="")
    position = models.CharField(max_length=20,
                                choices=POSITION_CHOICES,
                                default="BSII",)
    hours = models.IntegerField(default=35, validators=[MaxValueValidator(35)])
    quad = models.IntegerField(blank=True,
                                null=True,
                                choices=QUAD_CHOICES)
    isBuyer = models.BooleanField(default=False)

    def __str__(self):
        return self.lastName + ", " + self.firstName

    class Meta:
        ordering = ('lastName', 'firstName')

class WeekSchedule(models.Model):
    employee = models.ForeignKey(Employee, default="", on_delete=models.CASCADE)
    weekStart = models.DateField(default=datetime.date.today)
    mondayShift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)
    tuesdayShift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)
    wednesdayShift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)
    thursdayShift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)
    fridayShift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)
    saturdayShift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)
    sundayShift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)

class TempSchedule(models.Model):
    employee = models.ForeignKey(Employee, default="", on_delete=models.CASCADE)
    weekStart = models.DateField(default=datetime.date.today)
    mondayShift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)
    tuesdayShift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)
    wednesdayShift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)
    thursdayShift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)
    fridayShift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)
    saturdayShift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)
    sundayShift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)

class Request(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)

class VacationRequest(Request):
    startDate = models.DateField(default=datetime.date.today,)
    #                            validators=[no_past])
    endDate = models.DateField(default=datetime.date.today, )
    #                            validators=[no_past])
    
    def __str__(self):
        return self.employee + " : " + self.startDate

class ShiftRequest(Request):
    date = models.DateField(default=datetime.date.today, )
    #                        validators=[no_past])
    shift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)
    #recurring = models.BooleanField(default=False)

    def __str__(self):
        return self.employee + " : " + self.shift

class RecurringShiftRequest(Request):
    weekDay = models.CharField(default="M", max_length=10, choices=WEEKDAY_CHOICES)
    shift = models.CharField(max_length=15, default="", choices=SHIFT_CHOICES)

    def __str__(self):
        return self.employee + " : " + self.weekDay + self.shift

scheduler/forms.py
from django.forms import ModelForm
from django import forms
from .models import WeekSchedule, Employee, no_past, only_monday, WEEKDAY_CHOICES
from . import widgets

class NewEmployeeForm(ModelForm):
    class Meta:
        model = Employee
        fields = ['lastName', 'firstName', 'position', 'hours', 'quad']

    def process(self):
        cd = self.cleaned_data
        print(cd['firstName'])

class GenerateScheduleForm(forms.Form):
    currentWeek = forms.DateField(required=True, label="For the week of ", widget=forms.TextInput(attrs={'autocomplete':'off'}))
    #currentWeek = forms.DateField(required=True, label="For the week of ", widget=forms.TextInput(attrs={'type': 'week'}))
    coreGroupMeeting = forms.BooleanField(required=False, label="")
    coreGroupMeetingDay = forms.ChoiceField(choices=WEEKDAY_CHOICES, initial="M", label="Core Group Meeting", widget=forms.Select(attrs={'disabled':'disabled'}))
    staffMeeting = forms.BooleanField(required=False, label="")
    staffMeetingI = forms.ChoiceField(choices=WEEKDAY_CHOICES, initial="Th", label="Staff Meeting I", widget=forms.Select(attrs={'disabled':'disabled'}))
    staffMeetingII = forms.ChoiceField(choices=WEEKDAY_CHOICES, initial="F", label="Staff Meeting II", widget=forms.Select(attrs={'disabled':'disabled'}))
    quadOneMeeting = forms.BooleanField(required=False, label="")
    quadOneMeetingDay = forms.ChoiceField(choices=WEEKDAY_CHOICES, initial="M", label="Quad One", widget=forms.Select(attrs={'disabled':'disabled'}))
    quadTwoMeeting = forms.BooleanField(required=False, label="")
    quadTwoMeetingDay = forms.ChoiceField(choices=WEEKDAY_CHOICES, initial="T", label="Quad Two", widget=forms.Select(attrs={'disabled':'disabled'}))
    quadThreeMeeting = forms.BooleanField(required=False, label="")
    quadThreeMeetingDay = forms.ChoiceField(choices=WEEKDAY_CHOICES, initial="W", label="Quad Three", widget=forms.Select(attrs={'disabled':'disabled'}))
    quadFourMeeting = forms.BooleanField(required=False, label="")
    quadFourMeetingDay = forms.ChoiceField(choices=WEEKDAY_CHOICES, initial="Th", label="Quad Four", widget=forms.Select(attrs={'disabled':'disabled'}))

class WeekScheduleForm(ModelForm):
    class Meta:
        model = WeekSchedule
        fields = ['employee', 'mondayShift', 'tuesdayShift', 'wednesdayShift', 'thursdayShift', 'fridayShift', 'saturdayShift', 'sundayShift']

    def __init__(self, *args, **kwargs):
        super(WeekScheduleForm, self).__init__(*args, **kwargs)
        if self.instance.id:
            self.fields['employee'].disabled = True

scheduler/templates/scheduler/employee_update_form.html
{% include "scheduler/base.html" %}
{% include "scheduler/menu.html" %}

<body class="employees">
    <div class="container make-full-page">
        <div class="row">
            <div class="col-xs-12 center-block text-center">
                <div class="model-form-background">
                    <div class="col-xs-12 text-center">
                        <h4 class="sub-page-title page-top">Edit Employee</h4>
                    </div><!--col-->
                    <div class="col-xs-12 model-form text-center center-block">
                        <form method="POST">
                        {% csrf_token %}
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <label for="id_firstName">First Name: </label> {{ form.firstName }}
                                </div> 
                            </div><!--row-->
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <label for="id_lastName">Last Name: </label> {{ form.lastName }}
                                </div><!--col-->
                            </div><!--row-->
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <label for="id_position" class="input-label-padding">Position: </label> {{ form.position }}
                                </div><!--col-->
                            </div><!--row-->
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <label for="id_hours">Hours per Week: </label> {{ form.hours }}
                                </div><!--col-->
                            </div><!--row-->
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <label for="id_quad" class="input-label-padding">Quad: </label> {{ form.quad }}
                                </div><!--col-->
                            </div><!--row-->
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <label for="id_quad">Can Buy: </label> {{ form.isBuyer }}
                                </div><!--col-->
                            </div><!--row-->
                            <div class="row">
                                <div class="col-xs-12 text-center button-row">
                                    <input class="submit-button small-submit-button" type="submit" value="Update" />
                                </div><!--col-->
                            </div><!--row-->
                        </form>
                    </div><!--col-->
                </div><!--model-form-background-->
            </div><!--col-12-->
        </div><!--row-->
    </div><!--container-->
</body>

{% include "scheduler/footer.html" %}

scheduler/templates/scheduler/footer.html
<body>
    <div class="container" id="footer-container">
        <div class="row">
            <div class="col-xs-12 center-block text-center">
                <!--<p id="footer">Copyright © 2018 Carolyn Chan</p>-->
                <p id="footer">Carolyn Chan &nbsp; | &nbsp; 2019</p>
            </div><!--col-12-->
        </div><!--row-->
    </div><!--container-->
</body>

scheduler/templates/scheduler/generate-schedule.html
{% include "scheduler/base.html" %}
{% include "scheduler/menu.html" %}

<body class="generate">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h4 class="page-top sub-page-title text-center">Generated Schedule for {{ date | date:'M d, Y' }}</h4>
            </div>
            <div class="col-xs-12">
                <!--<div class="overflow-container">-->
                <div class="schedule-container">
                    <table class="schedule-table schedule-width">
                    <tr>
                        {% load custom_tags %}
                        <th>Employee</th>
                        <th>Monday   <br>{{ date | date:'m/d' }}</th>
                        <th>Tuesday  <br>{{ date | plus_days:1 | date:'m/d' }}</th>
                        <th>Wednesday<br>{{ date | plus_days:2 | date:'m/d' }}</th>
                        <th>Thursday <br>{{ date | plus_days:3 | date:'m/d' }}</th>
                        <th>Friday   <br>{{ date | plus_days:4 | date:'m/d' }}</th>
                        <th>Saturday <br>{{ date | plus_days:5 | date:'m/d' }}</th>
                        <th>Sunday   <br>{{ date | plus_days:6 | date:'m/d' }}</th>
                    </tr>
                    {% for schedule in temp_schedule_list %}
                    <tr>
                        <td> {{ schedule.employee }}</td>
                        <td> {{ schedule.get_mondayShift_display }}</td>
                        <td> {{ schedule.get_tuesdayShift_display }}</td>
                        <td> {{ schedule.get_wednesdayShift_display }}</td>
                        <td> {{ schedule.get_thursdayShift_display }}</td>
                        <td> {{ schedule.get_fridayShift_display }}</td>
                        <td> {{ schedule.get_saturdayShift_display }}</td>
                        <td> {{ schedule.get_sundayShift_display }}</td>
                    </tr>
                    {% endfor %}
                    </table>
                </div>
                <!--</div><!--overflow container-->
            </div>
            <div class="col-xs-12 text-center">
                <!-- Delete Button -->
                <form action="{% url 'scheduler:temp-schedule-delete' %}" class="inline-block generate-button" method="post">
                {% csrf_token %}
                    <button class="submit-button" type="submit" onclick="return confirm('Delete Schedule?');">Delete</button>
                </form>
                
                <!-- Save Button -->
                {% if override_flag %}
                    <form action="{% url 'scheduler:schedule-override' %}" class="inline-block generate-page-button" method="post">
                    {% csrf_token %}
                        <button class="submit-button" type="submit" onclick="return confirm('You have already saved a schedule for this week. Would you like to override the existing schedule?');">Save</button>
                    </form>
                {% else %}
                    <form action="{% url 'scheduler:schedule-save' %}" class="inline-block generate-page-button" method="post">
                    {% csrf_token %}
                        <button class="submit-button" type="submit" onclick="return confirm('Save Schedule?');">Save</button>
                    </form>
                {% endif %}
            </div><!--col-->
        </div><!--row-->
    </div><!--container-->
</body>

scheduler/templates/scheduler/index.html
{% include "scheduler/base.html" %}
{% include "scheduler/menu.html" %}
{% load staticfiles %}
<!--<script src="{% static 'js/jquery.weekpicker.js' %}"></script>-->
<script src="{% static 'js/weekPicker.js' %}"></script>
<link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/flick/jquery-ui.css">

<body class="generate">
    <div class="container make-full-page">
        <div class="row">
            <div class="col-xs-12 center-block text-center">
                <h1 class="page-title">Create Schedule</h1>
            </div><!--col-->
        </div><!--row-->
        <div class="row">
            <!--<p>For the week of: <input type="week" /></p>-->
            <form id="generate-form" action="{% url 'scheduler:index' %}" method="post">
            {% csrf_token %}    
                <div class="row">
                    <div id="week-div" class="col-xs-12 center-block text-center">
                        <label for="id_currentWeek">For the week of </label>
                        {{ form.currentWeek }}
                    </div><!--col-12-->
                </div><!--row-->
                <div class="meeting-div sub-div">
                    <div class="row">
                        <div class="col-xs-12 center-block">
                            <h4 class="subtitle">Staff Meetings</h4>
                            <div class="col-xs-6">
                                {{ form.coreGroupMeeting }}
                                <label for="id_coreGroupMeetingDay">Core Group Meeting: </label>
                                {{ form.coreGroupMeetingDay }}
                            </div><!--col-6-->
                            <div class="col-xs-6">
                                <div class="row">
                                    <div class="col-xs-1">
                                        {{ form.staffMeeting }}
                                    </div><!--col-1-->
                                    <div class="col-xs-10">
                                        <ul>
                                            <li><label for="id_staffMeetingI">Staff Meeting I: </label> {{ form.staffMeetingI }}</li>
                                            <li><label for="id_staffMeetingII">Staff Meeting II: </label> {{ form.staffMeetingII }}</li>
                                        </ul>
                                    </div><!--col-10-->
                                </div><!--row-->
                            </div><!--col-6-->
                        </div><!--col-12-->
                    </div><!--row-->
                </div><!--meeting-div-->
                <div class="meeting-div sub-div">
                    <div class="row">
                        <div class="col-xs-12 center-block">
                            <h4 class="subtitle">Quad Meetings</h4>
                            <div class="col-xs-6">
                                <ul>
                                    <li>{{ form.quadOneMeeting }}<label for="id_quadOneMeetingDay">Quad One: </label> {{ form.quadOneMeetingDay }}</li>
                                    <li>{{ form.quadTwoMeeting }}<label for="id_quadTwoMeetingDay">Quad Two: </label> {{ form.quadTwoMeetingDay }}</li>
                                </ul>
                            </div>
                            <div class="col-xs-6">
                                <ul>
                                        <li>{{ form.quadThreeMeeting }}<label for="id_quadThreeMeetingDay">Quad Three: </label> {{ form.quadThreeMeetingDay }}</li>
                                        <li>{{ form.quadFourMeeting }}<label for="id_quadFourMeetingDay">Quad Four: </label> {{ form.quadFourMeetingDay }}</li>
                                </ul>
                            </div>
                        </div><!--col-12-->
                    </div><!--row-->    
                </div><!--meeting-div-->       
                <!--<h3>Active Schedule Requests</h3>-->
                <br/>
                <div class="row">
                    <div class="col-xs-12 center-block text-center">
                        <input id="generate-button" class="submit-button" type="submit" value="Generate"/>
                    </div><!--col-12-->
                </div><!--row-->
            </form>
        </div><!--row-->
    </div><!--container-->
</body>
{% include "scheduler/footer.html" %}

<script>
        $('#id_coreGroupMeeting').on('change',function(e){
            if ($(this).is(':checked')){
                $('#id_coreGroupMeetingDay').removeAttr('disabled');
            }else{
                $('#id_coreGroupMeetingDay').attr('disabled','disabled');
            }
        });

        $('#id_staffMeeting').on('change',function(e){
            if ($(this).is(':checked')){
                $('#id_staffMeetingI').removeAttr('disabled');
                $('#id_staffMeetingII').removeAttr('disabled');
            }else{
                $('#id_staffMeetingI').attr('disabled','disabled');
                $('#id_staffMeetingII').attr('disabled','disabled');
            }
        });

        $('#id_quadOneMeeting').on('change',function(e){
            if ($(this).is(':checked')){
                $('#id_quadOneMeetingDay').removeAttr('disabled');
            }else{
                $('#id_quadOneMeetingDay').attr('disabled','disabled');
            }
        });

        $('#id_quadTwoMeeting').on('change',function(e){
            if ($(this).is(':checked')){
                $('#id_quadTwoMeetingDay').removeAttr('disabled');
            }else{
                $('#id_quadTwoMeetingDay').attr('disabled','disabled');
            }
        });

        $('#id_quadThreeMeeting').on('change',function(e){
            if ($(this).is(':checked')){
                $('#id_quadThreeMeetingDay').removeAttr('disabled');
            }else{
                $('#id_quadThreeMeetingDay').attr('disabled','disabled');
            }
        });

        $('#id_quadFourMeeting').on('change',function(e){
            if ($(this).is(':checked')){
                $('#id_quadFourMeetingDay').removeAttr('disabled');
            }else{
                $('#id_quadFourMeetingDay').attr('disabled','disabled');
            }
        });

        $('#generate-form').submit(function(){
            $("#generate-form :disabled").removeAttr('disabled');
        });

        convertToWeekPicker($("#id_currentWeek"));

        // Default calendar date is the Monday of this week
        var today = new Date();
        today = getMonday(today);
        month = ('0'+ (today.getMonth()+1)).slice(-2);
        day = ('0'+today.getDate()).slice(-2);
        year = today.getFullYear().toString().substr(2);
        today = month+'/'+day+'/'+year
        $("#id_currentWeek").val(today)
        
</script>

scheduler/templates/scheduler/recurringshiftrequest_form.html
{% include "scheduler/base.html" %}
{% include "scheduler/menu.html" %}

<body class="requests">
    <div class="container make-full-page">
        <div class="row">
            <div class="col-xs-12 center-block text-center">
                <div class="model-form-background">
                    <div class="col-xs-12 text-center">
                        <h4 class="sub-page-title page-top">New Recurring Shift Request</h4>
                    </div><!--col-12-->
                    <div class="col-xs-12 model-form text-center center-block">
                        <form action="{% url 'scheduler:recurring-shift-request' %}" method="POST">
                        {% csrf_token %}
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <label for="id_employee" class="input-label-padding">Employee: </label> {{ form.employee }}
                                </div> 
                            </div><!--row-->
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <label for="id_weekDay">Weekday: </label> {{ form.weekDay }}
                                </div><!--col-->
                            </div><!--row-->
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    <label for="id_shift">Shift: </label> {{ form.shift }}
                                </div><!--col-->
                            </div><!--row-->
                            <div class="row">
                                <div class="col-xs-12 text-center button-row">
                                    <input class="submit-button small-submit-button" type="submit" value="Create" />
                                </div><!--col-->
                            </div><!--row-->
                        </form>
                    </div><!--col-->
                </div><!--model-form-background-->
            </div><!--col-12-->
        </div><!--row-->
    </div><!--container-->
</body>

{% include "scheduler/footer.html" %}

scheduler/templates/scheduler/request-prompt.html
{% include "scheduler/base.html" %}
{% include "scheduler/menu.html" %}

<body class="requests">
    <div class="container make-full-page">
        <div class="row">
            <div class="col-xs-12 text-center">
                <h4 class="sub-page-title page-top">What type of request would you like to create?</h4>
            </div><!--col-->
            <div class="col-xs-12 text-center">
                <form action="{% url 'scheduler:vacation-request' %}">
                    <input type="submit" class="submit-button" value="Vacation Request"></input>
                </form>
                <form action="{% url 'scheduler:shift-request' %}">
                    <input type="submit" class="submit-button" value="Shift Request"></input>
                </form>
                <form action="{% url 'scheduler:recurring-shift-request' %}">
                    <input type="submit" class="submit-button" value="Recurring Shift Request"></input>
                </form>
            </div><!--col-->
        </div><!--row-->
    </div><!--container-->
</body>

{% include "scheduler/footer.html" %}